#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { execSync } from 'node:child_process'
import { callCloud, notConnected, readCloudConfig } from './lovabee-cloud.mjs'

const config = readCloudConfig()
if (!config) notConnected('npm run db:types')

const { types } = await callCloud(config, 'types')
const target = path.join(process.cwd(), 'src', 'shared', 'types', 'database.ts')
fs.writeFileSync(target, `// Generated by \`npm run db:types\` from the live database. Do not edit by hand.\n${types}`)
execSync(`npx prettier --write ${JSON.stringify(target)}`, { stdio: 'ignore' })
console.log(`✔ Wrote ${path.relative(process.cwd(), target)}`)
